<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace vaninsky\rlock\models\base;

use Yii;

/**
 * This is the base-model class for table "translate".
 *
 * @property integer $id
 * @property string $lang
 * @property string $table_name
 * @property integer $item_id
 * @property string $field_name
 * @property string $translate
 * @property string $aliasModel
 */
abstract class TranslateDb extends \yii\db\ActiveRecord
{
    public static $translatable = false;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'translate_db';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['lang', 'table_name', 'item_id'], 'required'],
            [['item_id'], 'integer'],
            [['translate'], 'string'],
            [['lang'], 'string', 'max' => 10],
            [['table_name', 'field_name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'lang' => 'Lang',
            'table_name' => 'Table Name',
            'item_id' => 'Item ID',
            'field_name' => 'Field Name',
            'translate' => 'Translate',
        ];
    }




}
